##### Pandas Method 5 august

In [17]:
# pandas method [pd]
# it is  dat manipulation librery
#performance operation / makeing any changes using pandas
# dataframe is collection of rows and columns

In [18]:
import pandas as pd

In [19]:
import pandas as pd

dicts ={"name" :["sandy","savi","vaibhav"],
        "age" :[21,1,25],
        "gender":["female","female","male"]
       }
dicts

{'name': ['sandy', 'savi', 'vaibhav'],
 'age': [21, 1, 25],
 'gender': ['female', 'female', 'male']}

In [20]:
#converting the dicts as a table using pandas
# dataframe : convert dicts/joson/array/so on data in to dataframe
#dataframe = df

df = pd.DataFrame(dicts)
df

      name  age  gender
0    sandy   21  female
1     savi    1  female
2  vaibhav   25    male

In [21]:
lists =[1,2,3,4,5,5]
lists_df = pd.DataFrame(lists)
lists_df

   0
0  1
1  2
2  3
3  4
4  5
5  5

In [22]:
lists =[1,2,3,4,5,5]
lists_df = pd.DataFrame(lists,columns = ["numbers"])
lists_df

   numbers
0        1
1        2
2        3
3        4
4        5
5        5

In [23]:
#method 2: read_csv :load the datset

In [24]:
#method 3: head():used to dispaly first 5 rows
df.head()

      name  age  gender
0    sandy   21  female
1     savi    1  female
2  vaibhav   25    male

In [25]:
#method 4: tail(): used to print or display last 5 rows
df.tail()

      name  age  gender
0    sandy   21  female
1     savi    1  female
2  vaibhav   25    male

In [26]:
#method 5: sample(): used to display rendom rows
df.sample()

      name  age gender
2  vaibhav   25   male

In [27]:
#method 6:shape:used to check the size of the dataset

df.shape # rows and columns

(3, 3)

In [28]:
#method 7:info() used to check the inforation about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [29]:
#method 8:columns:check the columns name of the dataset
df.columns

Index(['name', 'age', 'gender'], dtype='object')

In [30]:
#method 9: dtype:check the all columns of datatype

df.dtypes

name      object
age        int64
gender    object
dtype: object

In [31]:
# method 10:is null(): check missing value isnull()

df.isnull()

    name    age  gender
0  False  False   False
1  False  False   False
2  False  False   False

In [32]:
df.isnull().sum()

name      0
age       0
gender    0
dtype: int64

In [33]:
# method 11: isna() check the missing value

df.isna().sum()

name      0
age       0
gender    0
dtype: int64

In [34]:
# method 12: select the single columns

Target = df["target"]

KeyError: 'target'

In [ ]:
#method 13: select multiple columns

df [["age","sex","cp"]]

In [ ]:
#method 14:select the specific type of columINT
int_column = df.select_dtypes(include =["int"]).columns

In [ ]:
# length

len(float_column)

In [ ]:
#method 15: discribe():show the stastic summary of dataset

df.describe()

In [ ]:
#method 16: drop() drop the column

df.drop("exang",axis =1)

In [ ]:
#method 17: duplicted() : check the dupliceted velue

df.duplicated().sum()

In [2]:
#method 18: drop duplicated(): drop diplicated value

df.drop_duplicates().sum()

NameError: name 'df' is not defined

In [ ]:
#method 19: value count():

df["target"].value_counts()

# task on 5 august

In [ ]:
import pandas as pd

In [ ]:
DataFrame = df

In [ ]:
#1
df = pd.read_csv("C:\\Users\SANDY\Downloads\Bank_customer_churn.csv")
df

In [ ]:
#2
df.head(8)

In [ ]:
#3
df.tail(12)

In [ ]:
#4
df.sample(10)

In [ ]:
#5
df.shape

In [ ]:
#6
df.info()

In [ ]:
#7
df.columns

In [ ]:
#8
df.dtypes

In [ ]:
# 9

df.isnull().sum()

In [ ]:
#9

df.isna().sum()

In [ ]:
#10
CreditScore = df['CreditScore']

In [ ]:
# 11
df[["CustomerId","Surname","Balance","Exited"]]

In [ ]:
#12
import numpy as np
df.select_dtypes(include =[np.number])

In [ ]:
#13
df.describe()

In [ ]:
#14
df.duplicated().sum()

In [ ]:
#15:
df.value_counts()

# operators + loops

In [ ]:
#1 Take two numbers from user. Perform all arithmetic operations and also check
#which number is greater using comparison operators.

A = int(input("enter the number:"))
B = int(input("enter the number:"))

print("addition =",A + B)
print("subtraction =",A - B)
print("mutiplication =",A * B)
print("division =",A / B)
print("floor division =",A // B)
print("modulus =",A % B)
print("power =",A ** B)

if A > B:
    print(A, "is greater")
elif B > A:
    print(B," is greater")
else:
    print("both numbers are equal")

In [ ]:
# 2

for i in range(1 , 51):

    if i == 40:
        break
    if i % 5 == 0:
        continue
    print(i)

In [ ]:
#3
sum = 0
count = 0

while True:
    num = int(input("enter the number:"))

    if num > 0:
        break
    sum += num
    count +=1
if count > 0:
    print("sum =",sum)
    print("Average =",sum /count)

else:
    print("no numbers entered")

In [ ]:
# 4
for i in range(5,0,-1):
    for j in range(i):
        print("*",end ="")
    print()

In [ ]:
#5 
num = int(input("enter the number:"))
fact = 1
for i in range(1,num + 1):
    fact = fact * i
print("Factorial =",fact)

# while loop

In [ ]:
num = int(input("enter the value:"))

fact = 1
i = 1
while i < num:
    fact = fact * i
    i += 1
print("Factorial =",fact)

In [ ]:
#6
text =input("enter the text")

print("UpperCase:",text.upper())
print("Count of:",text.count("a"))
print("replace:",text.replace("  ","-"))
print("starts with Hello:",text.startswith("Hello"))

In [ ]:
## 7
lists =[1,2,3,4,5,6]

lists
lists.append(70)
print("Append:",lists)
lists.insert(0,12)
print("insert:",lists)
lists.remove(70)
print("remove:",lists)
lists.pop()
print("pop:",lists)
lists.sort(reverse=True)
print("Desending:",lists)
lists.reverse()
print("reverse:",lists)

In [ ]:
#8
dicts ={
    "sandy" : 89,
    "savi" : 97,
    "vaibhav":76,
    "sandeep":83,
    "santosh":55
}
for name,marks in dicts.items():
    if marks > 80:
        print(name,marks)

In [ ]:
#9
set1 = {1,2,3,4,5}
set2 ={6,7,8,9,10}

print("Union:",set1.union(set2))
print("Intersection:",set1.intersection(set2))
print("Difference:",set1.difference(set2))
set1.add(12)
print("after add:",set1)
set1.discard(2)
print("after discard:",set1)

In [ ]:
#10
class Student:
    def __init__(self):
        self.__marks = 0
    def set_marks(self,marks):
        if 0<= marks <= 100:
            self.__marks = marks
        else:
            print("Invalid Marks")

    def get_marks(self):
        return self.__marks
s = Student()
s.set_marks(75)
print("Marks:",s.get_marks())

# Renamind and type conversion  6 aug

# method 19:rename() : change the column name

i

In [ ]:
import pandas as pd
DataFrame = df

In [ ]:
df = pd.read_csv("C:\\Users\SANDY\Downloads\dataset.csv")
df

In [ ]:
df.rename (columns ={"target":"Result","sex":"gender"},inplace =True)

In [ ]:
df.columns =[col.title() for col in df.columns]

In [ ]:
df.columns

In [ ]:
df.add_prefix("col_")

In [ ]:
#method 21 : astype(): change the type of column value 
# int -> float
#float -> int
#int/fload -> string
#bool ->

In [ ]:
df['Col_Oldpeak'].astype("int")

In [ ]:
df['Col_Oldpeak']

In [ ]:
import numpy as np
dicts1 = {"Age":[10,12,13,14,15, np.nan,34,np.nan,12,23,45,np.nan]}

In [ ]:
# DataFrame 
df =pd.DataFrame(dicts1)
df

In [ ]:
df['Age'].value_counts(dropna =False)

In [ ]:
#method 22: fillna():fill the missing value

df['Age'].fillna('unknown',inplace =True)

In [ ]:
df

# aug 7

In [ ]:
# feed forword technice: next null value is filled with previous value/repalce the missing value using previous value
# feed backword techice: replace the feauter value as a present value

In [ ]:
# knn K-nearest nighbour
#summation(Nearest value)
  #       ---------------
        #  total Nearest value

In [ ]:
import pandas as pd
DataFrame = df

In [ ]:
import numpy as np
dicts1 = {"Age":[10,12,13,14,15, np.nan,34,np.nan,12,23,45,np.nan]}

In [ ]:
df =pd.DataFrame(dicts1)
df

In [ ]:
Age_mean = df['Age'].mean()
Age_mean

In [ ]:
df.isnull().sum()
df

In [ ]:
# method 23: ffill
df = df['Age'].fillna(method ="ffill")
df

In [ ]:
# method 24:bfill:
df =df['Age'].fillna(method = "bfill",inplace = True)

In [ ]:
#method 25:dropna():drop the missing value
df.dropna(inplace =True)
df

In [ ]:
# method 26:notnull():check the  not missing value

df['Age'].notnull().sum()

# method 27: replace() :replace value with another value

In [ ]:
df = pd.read_csv("C:\\Users\SANDY\Downloads\Bank_customer_churn.csv")
df.head(5)

In [ ]:
# method 27: replace() :replace value with another value
df.replace({'Gender':{'Male':'1','Female':'0'}},inplace = True)
df

In [ ]:
df['Gender'].unique()

In [ ]:
#  method 28 :sorting()

#sort_values()-- sort the column value

df.sort_values("Age")

In [ ]:
df.sort_values('Age',ascending = False)

In [ ]:
# method 29: sort_index() sort the index

df.sort_index()

In [ ]:
df.sort_index(ascending = False)

In [ ]:
# GROUPING & AGGREGATIO
# min, max, count, mean, median

df.groupby("Gender")["Age"].mean()

In [ ]:
df.groupby("Geography")["Age"].mean()

In [ ]:
df.groupby(["Geography","Gender"])["Age"].mean()

In [ ]:
df["Age_level"] = ["older" if age > 45 else "young" for age in df['Age']]

In [ ]:
df["Age_level"].value_count()

# aug 8

In [ ]:
# dicts

dicts ={"Age":["12","23","43","sumit","42","67.4","61","56","rajesh","sandy","1,2345","1-2"]}

In [ ]:
df =pd.DataFrame(dicts)
df

In [ ]:
df.dtypes

In [ ]:
df['Age'].astype("int")   # string conver into numaric it will not convert

In [ ]:
# to_numeric() :
# syntax: pd.to_numeric("col",error ="coerce")

In [ ]:
A = "10"
type(A)    # used in pandas only

In [ ]:
# method 30: to_numeric()
df["Age"] = pd.to_numeric(df["Age"],errors ="coerce")
df

In [ ]:
# Date columns handling 

dict1 =({'date':['2024-01-15','2024-02-20','2024-03-25']})

In [ ]:
df = pd.DataFrame({'date':['2024-01-15','2024-02-20','2024-03-25']})
df

In [ ]:
df.dtypes

In [ ]:
# to_datetime(df[col],errors ="coerce")
df["date"] =pd.to_datetime(df["date"],formats = "%y-%m-%d")
df

In [ ]:
df.dtypes

In [ ]:
df =pd.DataFrame({'date':[
    '2024-01-15', #YYYY-MM-DD
    '15/01/2024', #
    '01-15-2024',#
    'Jan 15 2024',#
    '20240215', #
]})
df['date']=pd.to_datetime({'date':['2024-01-15','2024-02-20','2024-03-25']})
df

In [ ]:
# extract the without date time convert day,month,year
# without the convert datetime formate
#date column handeling

df = pd.DataFrame({'date':['2024-01-15','2024-02-20','2024-03-25']})
df

In [ ]:
df.dtypes

In [ ]:
# extract the without date time convert day,month,year

df["year"] =df['date'].str.split("-").str[0]
df["Months"]=df['date'].str.split("-").str[1]
df["days"]=df['date'].str.split("-").str[2]
df

In [ ]:
date ="2024-02-20"

date.split("-")

In [ ]:
date[0]

In [ ]:
for i in date:
    print(i)

In [ ]:
df['days'] =df['date'].dt.day
df['months'] =df['date'].dt.month
df['year'] =df['date'].dt.year
df

In [ ]:
df = pd.DataFrame({'date':['2024-01-15','2024-02-20','2024-03-25']})

df["date"] = pd.to_datetime(df['date'],yearfirst =True)
df

In [ ]:
# save the file

df.tocsv("Clean_data.csv")

In [ ]:
# dict 
df =pd.DataFrame({"price":["423677","$678990","$78933","$36849"]})
df

In [1]:
df.dtypes

NameError: name 'df' is not defined

In [ ]:
# remove the $ symbol
#handle the price column
# step 1:remove the $ string

DataFrame =df

df["price"] =df["price"].str.replace("$","")       #regx=False used to remove the error
df["price"] =df["price"].str.replace(",","")    #regx=False used to remove the error



#step 2: convert to_numaric
df['price'] =pd.to_numeric(df["price"],error = "coerce")

In [2]:
# method : iloc[start:stop]

In [3]:
import pandas as pd
dicts ={"Age":["12","23","43","sumit","42","67.4","61","56","rajesh","sandy","1,2345","1-2"]}
df =pd.DataFrame(dicts)
df

# iloc[start_rows,:stop_rows,start_col,:stop_col]
df.iloc[1:7]      # it follows the index

     Age
1     23
2     43
3  sumit
4     42
5   67.4
6     61

In [4]:
df.loc[1:5]    # follw the lable it will not follow the index

     Age
1     23
2     43
3  sumit
4     42
5   67.4

In [5]:
df = pd.read_csv("C:\\Users\SANDY\Downloads\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:
df.iloc[0:10,0:7]

   age  sex  cp  trestbps  chol  fbs  restecg
0   63    1   3       145   233    1        0
1   37    1   2       130   250    0        1
2   41    0   1       130   204    0        0
3   56    1   1       120   236    0        1
4   57    0   0       120   354    0        1
5   57    1   0       140   192    0        1
6   56    0   1       140   294    0        0
7   44    1   1       120   263    0        1
8   52    1   2       172   199    1        1
9   57    1   2       150   168    0        1

In [ ]:
df.loc["rows_lable","column_lable"]
df.iloc[start_rows_index:stop_rows_index,start_col_index:stop_rcol_index]

In [14]:
target = df.iloc[::-1]
target

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1

In [15]:
invalid_value =(
    df.loc[
        pd.to_numeric(df["income_usd"],error="corcer").isna(),
        "income_usd"
        ]
    .value_counts()
)
invalid_values

KeyError: 'income_usd'